-- Run once as the already-created USER_TRANSACT_SCHEMA in the application PDB.
-- DDL commits implicitly. If an object exists, STOP and inspect it; do not drop data.
-- User details remain in USER_INFO_SCHEMA, managed by userInfoServices.
-- USER_ID is a logical reference only: no cross-schema grants or foreign key.
-- MONTH_COUNT means a number of months, not a calendar-month number.

SET ECHO OFF
SET VERIFY OFF
SET DEFINE OFF
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE SEQUENCE USER_TRANSACT_SCHEMA.TRANSACTION_ID_SEQ
    START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 NOCYCLE CACHE 20;

CREATE TABLE USER_TRANSACT_SCHEMA."TRANSACTION" (
    ID NUMBER(19) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    MONTH_NAME VARCHAR2(9 CHAR) NOT NULL,
    MONTH_COUNT NUMBER(10) NOT NULL,
    AMOUNT NUMBER(19,2) NOT NULL,
    VERSION NUMBER(19) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    MODIFIED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT TRANSACTION_PK PRIMARY KEY (ID),
    CONSTRAINT TRANSACTION_ID_CK CHECK (ID BETWEEN 1 AND 9223372036854775807),
    CONSTRAINT TRANSACTION_USER_CK CHECK (USER_ID BETWEEN 1 AND 9223372036854775807),
    CONSTRAINT TRANSACTION_MONTH_CK CHECK (MONTH_NAME IN (
        'JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE',
        'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER')),
    CONSTRAINT TRANSACTION_COUNT_CK CHECK (MONTH_COUNT BETWEEN 1 AND 2147483647),
    CONSTRAINT TRANSACTION_AMOUNT_CK CHECK (AMOUNT >= 0),
    CONSTRAINT TRANSACTION_VERSION_CK CHECK (VERSION BETWEEN 0 AND 9223372036854775807)
);

CREATE INDEX USER_TRANSACT_SCHEMA.TRANSACTION_USER_IX
    ON USER_TRANSACT_SCHEMA."TRANSACTION" (USER_ID, ID);

COMMENT ON COLUMN USER_TRANSACT_SCHEMA."TRANSACTION".USER_ID IS 'Logical USER_INFO_SCHEMA user ID; API does not yet validate existence';
COMMENT ON COLUMN USER_TRANSACT_SCHEMA."TRANSACTION".MONTH_COUNT IS 'Positive number of months, not month-of-year';
COMMENT ON COLUMN USER_TRANSACT_SCHEMA."TRANSACTION".AMOUNT IS 'Entered amount; no currency conversion or multiplication is applied';
COMMENT ON COLUMN USER_TRANSACT_SCHEMA."TRANSACTION".VERSION IS 'Optimistic-lock version; include the last-read value in PUT requests';

PROMPT Transaction table, sequence and index created. No user records were inserted.
