-- Run as UI_DATA_SCHEMA after user-info-ui's shared DDL.
-- No user/schema creation. No application/user/transaction data is changed.
-- Insert-only MERGEs deliberately preserve later administrator enable/deny decisions.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF

MERGE INTO UI_DATA_SCHEMA.UI_COMPONENT_SERVER t
USING (SELECT 'transaction-ui' SERVER_CODE,'transaction-ui-component' SERVICE_ID,
              'http://127.0.0.1:8782/transaction-ui-component' BASE_URL FROM dual) s
ON (t.SERVER_CODE=s.SERVER_CODE)
WHEN NOT MATCHED THEN INSERT(SERVER_CODE,SERVICE_ID,BASE_URL,ENABLED)
VALUES(s.SERVER_CODE,s.SERVICE_ID,s.BASE_URL,1);

MERGE INTO UI_DATA_SCHEMA.UI_COMPONENT t
USING (SELECT 'transactions' COMPONENT_CODE, 'transaction-ui' SERVER_CODE,
              'transactions' RESOURCE_NAME,'Transactions' DISPLAY_NAME FROM dual) s
ON (t.COMPONENT_CODE=s.COMPONENT_CODE)
WHEN NOT MATCHED THEN INSERT (COMPONENT_CODE,SERVER_CODE,RESOURCE_NAME,DISPLAY_NAME,ENABLED)
VALUES(s.COMPONENT_CODE,s.SERVER_CODE,s.RESOURCE_NAME,s.DISPLAY_NAME,1);

MERGE INTO UI_DATA_SCHEMA.UI_ACTIVITY t
USING (
    SELECT 'UI_TRANSACTIONS' UI_ACTIVITY_CODE,'Transaction' LABEL,'transactions' VIEW_KEY,10 SORT_ORDER,1 ENABLED FROM dual
    UNION ALL SELECT 'UI_ITEM1','Item1','placeholder',20,0 FROM dual
    UNION ALL SELECT 'UI_ITEM2','Item2','placeholder',30,0 FROM dual
    UNION ALL SELECT 'UI_ITEM3','Item3','placeholder',40,0 FROM dual
    UNION ALL SELECT 'UI_ITEM4','Item4','placeholder',50,0 FROM dual
) s ON (t.UI_ACTIVITY_CODE=s.UI_ACTIVITY_CODE)
WHEN NOT MATCHED THEN INSERT(UI_ACTIVITY_CODE,COMPONENT_CODE,LABEL,VIEW_KEY,SORT_ORDER,ENABLED)
VALUES(s.UI_ACTIVITY_CODE,'transactions',s.LABEL,s.VIEW_KEY,s.SORT_ORDER,s.ENABLED);

MERGE INTO UI_DATA_SCHEMA.FUNCTIONAL_ACTIVITY t
USING (
    SELECT 'TXN_USERS_READ' FUNCTIONAL_ACTIVITY_CODE FROM dual
    UNION ALL SELECT 'TXN_LIST_READ' FROM dual
) s ON (t.FUNCTIONAL_ACTIVITY_CODE=s.FUNCTIONAL_ACTIVITY_CODE)
WHEN NOT MATCHED THEN INSERT(FUNCTIONAL_ACTIVITY_CODE,COMPONENT_CODE,ENABLED)
VALUES(s.FUNCTIONAL_ACTIVITY_CODE,'transactions',1);

MERGE INTO UI_DATA_SCHEMA.UI_COMPONENT_API t
USING (
    SELECT 'users' OPERATION_CODE,'/api/users' UPSTREAM_PATH,'TXN_USERS_READ' FUNCTIONAL_ACTIVITY_CODE,
           'USER_OPTIONS' RESPONSE_TYPE,'page,size' QUERY_PARAMETERS FROM dual
    UNION ALL SELECT 'transactions','/api/transactions','TXN_LIST_READ','TRANSACTION_PAGE','userId,page,size' FROM dual
) s ON (t.COMPONENT_CODE='transactions' AND t.OPERATION_CODE=s.OPERATION_CODE)
WHEN NOT MATCHED THEN INSERT(COMPONENT_CODE,OPERATION_CODE,UPSTREAM_PATH,UI_ACTIVITY_CODE,
                            FUNCTIONAL_ACTIVITY_CODE,RESPONSE_TYPE,QUERY_PARAMETERS,ENABLED)
VALUES('transactions',s.OPERATION_CODE,s.UPSTREAM_PATH,'UI_TRANSACTIONS',s.FUNCTIONAL_ACTIVITY_CODE,
       s.RESPONSE_TYPE,s.QUERY_PARAMETERS,1);

MERGE INTO UI_DATA_SCHEMA.ACTIVITY_GRANT t
USING (
    SELECT 'UI' ACTIVITY_KIND,'UI_TRANSACTIONS' ACTIVITY_CODE FROM dual
    UNION ALL SELECT 'UI','UI_ITEM1' FROM dual
    UNION ALL SELECT 'UI','UI_ITEM2' FROM dual
    UNION ALL SELECT 'UI','UI_ITEM3' FROM dual
    UNION ALL SELECT 'UI','UI_ITEM4' FROM dual
    UNION ALL SELECT 'FUNCTIONAL','TXN_USERS_READ' FROM dual
    UNION ALL SELECT 'FUNCTIONAL','TXN_LIST_READ' FROM dual
) s ON (t.ACTIVITY_KIND=s.ACTIVITY_KIND AND t.ACTIVITY_CODE=s.ACTIVITY_CODE
        AND t.SUBJECT_TYPE='ALL' AND t.SUBJECT_ID='*')
WHEN NOT MATCHED THEN INSERT(ACTIVITY_KIND,ACTIVITY_CODE,SUBJECT_TYPE,SUBJECT_ID,ALLOWED)
VALUES(s.ACTIVITY_KIND,s.ACTIVITY_CODE,'ALL','*',1);

COMMIT;
