-- Isolated H2 test fixture only; never included in the SQL ZIP or WAR.
CREATE SCHEMA IF NOT EXISTS USER_TRANSACT_SCHEMA;
CREATE SEQUENCE USER_TRANSACT_SCHEMA.TRANSACTION_ID_SEQ START WITH 1;
CREATE TABLE USER_TRANSACT_SCHEMA."TRANSACTION" (
  ID NUMBER(19) PRIMARY KEY,
  USER_ID NUMBER(19) NOT NULL CHECK (USER_ID > 0),
  MONTH_NAME VARCHAR2(9) NOT NULL CHECK (MONTH_NAME IN ('JANUARY','FEBRUARY','MARCH','APRIL','MAY','JUNE','JULY','AUGUST','SEPTEMBER','OCTOBER','NOVEMBER','DECEMBER')),
  MONTH_COUNT NUMBER(10) NOT NULL CHECK (MONTH_COUNT BETWEEN 1 AND 2147483647),
  AMOUNT NUMBER(19,2) NOT NULL CHECK (AMOUNT >= 0),
  VERSION NUMBER(19) DEFAULT 0 NOT NULL CHECK (VERSION >= 0),
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  MODIFIED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX USER_TRANSACT_SCHEMA.TRANSACTION_USER_IX ON USER_TRANSACT_SCHEMA."TRANSACTION"(USER_ID, ID);
